[package]
name = "shortcut-rs"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
config = "0.15.19"
serde = { version = "1.0.228", features = ["derive"] }
